language: java
jdk:
  - openjdk6
  - oraclejdk7
  - openjdk7
  - oraclejdk8
branches:
  only:
    - master
    - condast
    - mindarchitect
before_install: 'mvn -version'
install: 'mvn clean install -DskipTests'

